### ISSUE TITLE
Weird looking page when loaded in firefox

### ISSUE THREAD

**Issue by milomc123** [AmrBinBashir/Kura#1]
Hi!
I just tried to load Kura into firefox (I know its not supported but i wanted to anyway 😃) and it looked really weird, let me know if you need more info.
Loving Kura in chrome though!
![kura](https://user-images.githubusercontent.com/33701036/74860665-eef0eb00-5340-11ea-9aa6-4adc97e38271.PNG)
Here is the firefox XPI file:
[kura_new_tab-1.0.0-fx.zip](https://github.com/AmrBinBashir/Kura/files/4226544/kura_new_tab-1.0.0-fx.zip)

**Comment by AmrBinBashir** [comment]
@milomc123 before you build the extension for firefox make sure to remove "background" from permission list in manifest.json. I added this permission cause i like to keep my browser running in the background to get notifications from various websites but apparently it's not supported in firefox. So for now you can remove this permission and the extension should kinda work with some bugs here and there.

**Comment by AmrBinBashir** [comment]
@milomc123 the extension works fine out of the box for now but if you hit the save or reset buttons, it breaks the extension. so if you want to use it without modifying the settings go ahead but if you want to modify settings you will have to do it manually for now until i find what is causing this bug.
1- go to `about:debugging#/runtime/this-firefox`
2- click inspect on kura
3- go to storage tab and under extension storage , you will find one item , click on it , this will open a view next to it
4- in that view you will find a key name "userConfig", you can edit it as you want. some options will have to be one of these values 
```
     wallpaperSourceOptions: [
        "Bing Daily Wallpaper",
        "Unsplash Random Wallpaper",
        "Wallpaper From URL",
        "Local Wallpaper",
        "Solid Color"
      ],
      searchBoxStyleOptions: ["Box", "Line"],
      clockStyleOptions: ["Vertical", "Horizontal"],
      dateStyleOptions: ["Short", "Long"]
```
after you make changes reload the new tab page and if the background is still black hit the randomize icon in the bottom left.

**Comment by AmrBinBashir** [comment]
@milomc123 the bug is fixed now, pull the latest changes and rebuild the extension.

**Comment by milomc123** [comment]
@AmrBinBashir Thanks ill try it later!

**Comment by AmrBinBashir** [comment]
@milomc123 the extension is now on firefox store. Wouldn't have happen without you. thanks.

**Comment by milomc123** [comment]
@AmrBinBashir Thanks! It's working great! 
![Capture](https://user-images.githubusercontent.com/33701036/75037193-7e1a1200-54ab-11ea-902d-7ec353353642.PNG)
